version: '3.6'

services: 

# BACKEND API
  budget-api: 
    container_name: docker-backend
    image: node:8.11.1
    command: npm run start
    working_dir: /usr/src/budget-api
    environment:
      POSTGRES_URI:  postgres://boluwatife:boluwatife@postgres:5432/budget-docker
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/budget-api

# Postgres
  postgres:
    environment :
      POSTGRES_USER: boluwatife
      POSTGRES_PASSWORD: boluwatife
      POSTGRES_DB: budget-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports: 
      - "5432:5432"

# Redis 
  redis:
    image: redis
    ports: 
      - "6379:6379"
